name: DevSkim

on:
  push:
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**.yml"
      - "docs/**"
      - "**/*.md"
      - "**/*.yml"
  schedule:
    - cron: "34 13 * * 5"

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
